"""add collaborators table

Revision ID: 1398029e50e2
Revises: 187f861b0fe9
Create Date: 2025-11-16 19:40:33.956819

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1398029e50e2'
down_revision: Union[str, None] = '187f861b0fe9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('collaborators',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mindmap_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('invited_by', sa.UUID(), nullable=True),
    sa.Column('invited_at', sa.DateTime(), nullable=False),
    sa.Column('accepted_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['invited_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['mindmap_id'], ['mindmaps.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_collaborators_id'), 'collaborators', ['id'], unique=False)
    op.drop_index('idx_mindmaps_created_by', table_name='mindmaps')
    op.drop_index('idx_nodes_created_by', table_name='nodes')
    op.drop_index('idx_nodes_mindmap_id', table_name='nodes')
    op.drop_index('idx_votes_node_id', table_name='votes')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_votes_node_id', 'votes', ['node_id'], unique=False)
    op.create_index('idx_nodes_mindmap_id', 'nodes', ['mindmap_id'], unique=False)
    op.create_index('idx_nodes_created_by', 'nodes', ['created_by'], unique=False)
    op.create_index('idx_mindmaps_created_by', 'mindmaps', ['created_by'], unique=False)
    op.drop_index(op.f('ix_collaborators_id'), table_name='collaborators')
    op.drop_table('collaborators')
    # ### end Alembic commands ###
